// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockTokenParser is an autogenerated mock type for the TokenParser type
type MockTokenParser struct {
	mock.Mock
}

type MockTokenParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenParser) EXPECT() *MockTokenParser_Expecter {
	return &MockTokenParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function with given fields: token
func (_m *MockTokenParser) Parse(token string) (int64, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockTokenParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - token string
func (_e *MockTokenParser_Expecter) Parse(token interface{}) *MockTokenParser_Parse_Call {
	return &MockTokenParser_Parse_Call{Call: _e.mock.On("Parse", token)}
}

func (_c *MockTokenParser_Parse_Call) Run(run func(token string)) *MockTokenParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTokenParser_Parse_Call) Return(_a0 int64, _a1 error) *MockTokenParser_Parse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenParser_Parse_Call) RunAndReturn(run func(string) (int64, error)) *MockTokenParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenParser creates a new instance of MockTokenParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenParser {
	mock := &MockTokenParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
