with-expecter: true
disable-version-string: True
resolve-type-alias: False
issue-845-fix: True
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
filename: "mock_{{.InterfaceName | snakecase}}.go"
packages:
  taskmanager/internal/service:
    interfaces:
      UnitOfWork:
      UserRepository:
      PasswordHasher:
      TokenIssuer:
      TeamRepository:
      TeamMemberRepository:
      TeamUserRepository:
      TaskRepository:
      TaskHistoryRepository:
      MembershipRepository:
      TaskCache:
      CommentTaskRepository:
      CommentRepository:
  taskmanager/internal/http/middleware:
    interfaces:
      TokenParser:
  taskmanager/internal/http/auth_handler:
    interfaces:
      Registrar:
      Authenticator:
  taskmanager/internal/http/team_handler:
    interfaces:
      TeamCreator:
      TeamLister:
      TeamInviter:
  taskmanager/internal/http/task_handler:
    interfaces:
      TaskCreator:
      TaskLister:
      TaskUpdater:
      HistoryGetter:
      CommentAdder:
      CommentLister:
  taskmanager/internal/http/analytics_handler:
    interfaces:
      Analytics:
