// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "taskmanager/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockTeamCreator is an autogenerated mock type for the TeamCreator type
type MockTeamCreator struct {
	mock.Mock
}

type MockTeamCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamCreator) EXPECT() *MockTeamCreator_Expecter {
	return &MockTeamCreator_Expecter{mock: &_m.Mock}
}

// CreateTeam provides a mock function with given fields: ctx, ownerID, name
func (_m *MockTeamCreator) CreateTeam(ctx context.Context, ownerID int64, name string) (*entity.Team, error) {
	ret := _m.Called(ctx, ownerID, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 *entity.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (*entity.Team, error)); ok {
		return rf(ctx, ownerID, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) *entity.Team); ok {
		r0 = rf(ctx, ownerID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, ownerID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamCreator_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type MockTeamCreator_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID int64
//   - name string
func (_e *MockTeamCreator_Expecter) CreateTeam(ctx interface{}, ownerID interface{}, name interface{}) *MockTeamCreator_CreateTeam_Call {
	return &MockTeamCreator_CreateTeam_Call{Call: _e.mock.On("CreateTeam", ctx, ownerID, name)}
}

func (_c *MockTeamCreator_CreateTeam_Call) Run(run func(ctx context.Context, ownerID int64, name string)) *MockTeamCreator_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockTeamCreator_CreateTeam_Call) Return(_a0 *entity.Team, _a1 error) *MockTeamCreator_CreateTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamCreator_CreateTeam_Call) RunAndReturn(run func(context.Context, int64, string) (*entity.Team, error)) *MockTeamCreator_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamCreator creates a new instance of MockTeamCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamCreator {
	mock := &MockTeamCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
