// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	service "taskmanager/internal/service"

	mock "github.com/stretchr/testify/mock"
)

// MockTeamInviter is an autogenerated mock type for the TeamInviter type
type MockTeamInviter struct {
	mock.Mock
}

type MockTeamInviter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamInviter) EXPECT() *MockTeamInviter_Expecter {
	return &MockTeamInviter_Expecter{mock: &_m.Mock}
}

// Invite provides a mock function with given fields: ctx, cmd
func (_m *MockTeamInviter) Invite(ctx context.Context, cmd service.InviteCommand) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Invite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.InviteCommand) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamInviter_Invite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invite'
type MockTeamInviter_Invite_Call struct {
	*mock.Call
}

// Invite is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd service.InviteCommand
func (_e *MockTeamInviter_Expecter) Invite(ctx interface{}, cmd interface{}) *MockTeamInviter_Invite_Call {
	return &MockTeamInviter_Invite_Call{Call: _e.mock.On("Invite", ctx, cmd)}
}

func (_c *MockTeamInviter_Invite_Call) Run(run func(ctx context.Context, cmd service.InviteCommand)) *MockTeamInviter_Invite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.InviteCommand))
	})
	return _c
}

func (_c *MockTeamInviter_Invite_Call) Return(_a0 error) *MockTeamInviter_Invite_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamInviter_Invite_Call) RunAndReturn(run func(context.Context, service.InviteCommand) error) *MockTeamInviter_Invite_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamInviter creates a new instance of MockTeamInviter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamInviter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamInviter {
	mock := &MockTeamInviter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
