// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "taskmanager/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockTeamLister is an autogenerated mock type for the TeamLister type
type MockTeamLister struct {
	mock.Mock
}

type MockTeamLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamLister) EXPECT() *MockTeamLister_Expecter {
	return &MockTeamLister_Expecter{mock: &_m.Mock}
}

// ListTeams provides a mock function with given fields: ctx, userID
func (_m *MockTeamLister) ListTeams(ctx context.Context, userID int64) ([]entity.Team, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListTeams")
	}

	var r0 []entity.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]entity.Team, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []entity.Team); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamLister_ListTeams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTeams'
type MockTeamLister_ListTeams_Call struct {
	*mock.Call
}

// ListTeams is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockTeamLister_Expecter) ListTeams(ctx interface{}, userID interface{}) *MockTeamLister_ListTeams_Call {
	return &MockTeamLister_ListTeams_Call{Call: _e.mock.On("ListTeams", ctx, userID)}
}

func (_c *MockTeamLister_ListTeams_Call) Run(run func(ctx context.Context, userID int64)) *MockTeamLister_ListTeams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTeamLister_ListTeams_Call) Return(_a0 []entity.Team, _a1 error) *MockTeamLister_ListTeams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamLister_ListTeams_Call) RunAndReturn(run func(context.Context, int64) ([]entity.Team, error)) *MockTeamLister_ListTeams_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamLister creates a new instance of MockTeamLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamLister {
	mock := &MockTeamLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
