// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "taskmanager/internal/entity"
	service "taskmanager/internal/service"

	mock "github.com/stretchr/testify/mock"
)

// MockTaskCreator is an autogenerated mock type for the TaskCreator type
type MockTaskCreator struct {
	mock.Mock
}

type MockTaskCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskCreator) EXPECT() *MockTaskCreator_Expecter {
	return &MockTaskCreator_Expecter{mock: &_m.Mock}
}

// CreateTask provides a mock function with given fields: ctx, cmd
func (_m *MockTaskCreator) CreateTask(ctx context.Context, cmd service.CreateTaskCommand) (*entity.Task, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *entity.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.CreateTaskCommand) (*entity.Task, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.CreateTaskCommand) *entity.Task); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.CreateTaskCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskCreator_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockTaskCreator_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd service.CreateTaskCommand
func (_e *MockTaskCreator_Expecter) CreateTask(ctx interface{}, cmd interface{}) *MockTaskCreator_CreateTask_Call {
	return &MockTaskCreator_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, cmd)}
}

func (_c *MockTaskCreator_CreateTask_Call) Run(run func(ctx context.Context, cmd service.CreateTaskCommand)) *MockTaskCreator_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.CreateTaskCommand))
	})
	return _c
}

func (_c *MockTaskCreator_CreateTask_Call) Return(_a0 *entity.Task, _a1 error) *MockTaskCreator_CreateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskCreator_CreateTask_Call) RunAndReturn(run func(context.Context, service.CreateTaskCommand) (*entity.Task, error)) *MockTaskCreator_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskCreator creates a new instance of MockTaskCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskCreator {
	mock := &MockTaskCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
