// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "taskmanager/internal/entity"
	service "taskmanager/internal/service"

	mock "github.com/stretchr/testify/mock"
)

// MockTaskLister is an autogenerated mock type for the TaskLister type
type MockTaskLister struct {
	mock.Mock
}

type MockTaskLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskLister) EXPECT() *MockTaskLister_Expecter {
	return &MockTaskLister_Expecter{mock: &_m.Mock}
}

// ListTasks provides a mock function with given fields: ctx, query
func (_m *MockTaskLister) ListTasks(ctx context.Context, query service.ListTasksQuery) ([]entity.Task, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 []entity.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.ListTasksQuery) ([]entity.Task, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.ListTasksQuery) []entity.Task); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.ListTasksQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskLister_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type MockTaskLister_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - query service.ListTasksQuery
func (_e *MockTaskLister_Expecter) ListTasks(ctx interface{}, query interface{}) *MockTaskLister_ListTasks_Call {
	return &MockTaskLister_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx, query)}
}

func (_c *MockTaskLister_ListTasks_Call) Run(run func(ctx context.Context, query service.ListTasksQuery)) *MockTaskLister_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.ListTasksQuery))
	})
	return _c
}

func (_c *MockTaskLister_ListTasks_Call) Return(_a0 []entity.Task, _a1 error) *MockTaskLister_ListTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskLister_ListTasks_Call) RunAndReturn(run func(context.Context, service.ListTasksQuery) ([]entity.Task, error)) *MockTaskLister_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskLister creates a new instance of MockTaskLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskLister {
	mock := &MockTaskLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
