// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "taskmanager/internal/entity"
	service "taskmanager/internal/service"

	mock "github.com/stretchr/testify/mock"
)

// MockTaskUpdater is an autogenerated mock type for the TaskUpdater type
type MockTaskUpdater struct {
	mock.Mock
}

type MockTaskUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskUpdater) EXPECT() *MockTaskUpdater_Expecter {
	return &MockTaskUpdater_Expecter{mock: &_m.Mock}
}

// UpdateTask provides a mock function with given fields: ctx, cmd
func (_m *MockTaskUpdater) UpdateTask(ctx context.Context, cmd service.UpdateTaskCommand) (*entity.Task, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 *entity.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.UpdateTaskCommand) (*entity.Task, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.UpdateTaskCommand) *entity.Task); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.UpdateTaskCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskUpdater_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type MockTaskUpdater_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd service.UpdateTaskCommand
func (_e *MockTaskUpdater_Expecter) UpdateTask(ctx interface{}, cmd interface{}) *MockTaskUpdater_UpdateTask_Call {
	return &MockTaskUpdater_UpdateTask_Call{Call: _e.mock.On("UpdateTask", ctx, cmd)}
}

func (_c *MockTaskUpdater_UpdateTask_Call) Run(run func(ctx context.Context, cmd service.UpdateTaskCommand)) *MockTaskUpdater_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.UpdateTaskCommand))
	})
	return _c
}

func (_c *MockTaskUpdater_UpdateTask_Call) Return(_a0 *entity.Task, _a1 error) *MockTaskUpdater_UpdateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskUpdater_UpdateTask_Call) RunAndReturn(run func(context.Context, service.UpdateTaskCommand) (*entity.Task, error)) *MockTaskUpdater_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskUpdater creates a new instance of MockTaskUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskUpdater {
	mock := &MockTaskUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
