// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "taskmanager/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockCommentAdder is an autogenerated mock type for the CommentAdder type
type MockCommentAdder struct {
	mock.Mock
}

type MockCommentAdder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommentAdder) EXPECT() *MockCommentAdder_Expecter {
	return &MockCommentAdder_Expecter{mock: &_m.Mock}
}

// AddComment provides a mock function with given fields: ctx, actorID, taskID, body
func (_m *MockCommentAdder) AddComment(ctx context.Context, actorID int64, taskID int64, body string) (*entity.TaskComment, error) {
	ret := _m.Called(ctx, actorID, taskID, body)

	if len(ret) == 0 {
		panic("no return value specified for AddComment")
	}

	var r0 *entity.TaskComment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string) (*entity.TaskComment, error)); ok {
		return rf(ctx, actorID, taskID, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string) *entity.TaskComment); ok {
		r0 = rf(ctx, actorID, taskID, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TaskComment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, string) error); ok {
		r1 = rf(ctx, actorID, taskID, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentAdder_AddComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddComment'
type MockCommentAdder_AddComment_Call struct {
	*mock.Call
}

// AddComment is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID int64
//   - taskID int64
//   - body string
func (_e *MockCommentAdder_Expecter) AddComment(ctx interface{}, actorID interface{}, taskID interface{}, body interface{}) *MockCommentAdder_AddComment_Call {
	return &MockCommentAdder_AddComment_Call{Call: _e.mock.On("AddComment", ctx, actorID, taskID, body)}
}

func (_c *MockCommentAdder_AddComment_Call) Run(run func(ctx context.Context, actorID int64, taskID int64, body string)) *MockCommentAdder_AddComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(string))
	})
	return _c
}

func (_c *MockCommentAdder_AddComment_Call) Return(_a0 *entity.TaskComment, _a1 error) *MockCommentAdder_AddComment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommentAdder_AddComment_Call) RunAndReturn(run func(context.Context, int64, int64, string) (*entity.TaskComment, error)) *MockCommentAdder_AddComment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommentAdder creates a new instance of MockCommentAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommentAdder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommentAdder {
	mock := &MockCommentAdder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
