// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "taskmanager/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockHistoryGetter is an autogenerated mock type for the HistoryGetter type
type MockHistoryGetter struct {
	mock.Mock
}

type MockHistoryGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHistoryGetter) EXPECT() *MockHistoryGetter_Expecter {
	return &MockHistoryGetter_Expecter{mock: &_m.Mock}
}

// GetHistory provides a mock function with given fields: ctx, actorID, taskID
func (_m *MockHistoryGetter) GetHistory(ctx context.Context, actorID int64, taskID int64) ([]entity.TaskHistory, error) {
	ret := _m.Called(ctx, actorID, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 []entity.TaskHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) ([]entity.TaskHistory, error)); ok {
		return rf(ctx, actorID, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) []entity.TaskHistory); ok {
		r0 = rf(ctx, actorID, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TaskHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, actorID, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHistoryGetter_GetHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistory'
type MockHistoryGetter_GetHistory_Call struct {
	*mock.Call
}

// GetHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID int64
//   - taskID int64
func (_e *MockHistoryGetter_Expecter) GetHistory(ctx interface{}, actorID interface{}, taskID interface{}) *MockHistoryGetter_GetHistory_Call {
	return &MockHistoryGetter_GetHistory_Call{Call: _e.mock.On("GetHistory", ctx, actorID, taskID)}
}

func (_c *MockHistoryGetter_GetHistory_Call) Run(run func(ctx context.Context, actorID int64, taskID int64)) *MockHistoryGetter_GetHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockHistoryGetter_GetHistory_Call) Return(_a0 []entity.TaskHistory, _a1 error) *MockHistoryGetter_GetHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHistoryGetter_GetHistory_Call) RunAndReturn(run func(context.Context, int64, int64) ([]entity.TaskHistory, error)) *MockHistoryGetter_GetHistory_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHistoryGetter creates a new instance of MockHistoryGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHistoryGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHistoryGetter {
	mock := &MockHistoryGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
