// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "taskmanager/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockCommentLister is an autogenerated mock type for the CommentLister type
type MockCommentLister struct {
	mock.Mock
}

type MockCommentLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommentLister) EXPECT() *MockCommentLister_Expecter {
	return &MockCommentLister_Expecter{mock: &_m.Mock}
}

// ListComments provides a mock function with given fields: ctx, actorID, taskID
func (_m *MockCommentLister) ListComments(ctx context.Context, actorID int64, taskID int64) ([]entity.TaskComment, error) {
	ret := _m.Called(ctx, actorID, taskID)

	if len(ret) == 0 {
		panic("no return value specified for ListComments")
	}

	var r0 []entity.TaskComment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) ([]entity.TaskComment, error)); ok {
		return rf(ctx, actorID, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) []entity.TaskComment); ok {
		r0 = rf(ctx, actorID, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TaskComment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, actorID, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentLister_ListComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListComments'
type MockCommentLister_ListComments_Call struct {
	*mock.Call
}

// ListComments is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID int64
//   - taskID int64
func (_e *MockCommentLister_Expecter) ListComments(ctx interface{}, actorID interface{}, taskID interface{}) *MockCommentLister_ListComments_Call {
	return &MockCommentLister_ListComments_Call{Call: _e.mock.On("ListComments", ctx, actorID, taskID)}
}

func (_c *MockCommentLister_ListComments_Call) Run(run func(ctx context.Context, actorID int64, taskID int64)) *MockCommentLister_ListComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockCommentLister_ListComments_Call) Return(_a0 []entity.TaskComment, _a1 error) *MockCommentLister_ListComments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommentLister_ListComments_Call) RunAndReturn(run func(context.Context, int64, int64) ([]entity.TaskComment, error)) *MockCommentLister_ListComments_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommentLister creates a new instance of MockCommentLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommentLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommentLister {
	mock := &MockCommentLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
