// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "taskmanager/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockTeamUserRepository is an autogenerated mock type for the TeamUserRepository type
type MockTeamUserRepository struct {
	mock.Mock
}

type MockTeamUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamUserRepository) EXPECT() *MockTeamUserRepository_Expecter {
	return &MockTeamUserRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockTeamUserRepository) GetByID(ctx context.Context, id int64) (*entity.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamUserRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTeamUserRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockTeamUserRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTeamUserRepository_GetByID_Call {
	return &MockTeamUserRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTeamUserRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockTeamUserRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTeamUserRepository_GetByID_Call) Return(_a0 *entity.User, _a1 error) *MockTeamUserRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamUserRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*entity.User, error)) *MockTeamUserRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamUserRepository creates a new instance of MockTeamUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamUserRepository {
	mock := &MockTeamUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
