// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "taskmanager/internal/entity"
	repository "taskmanager/internal/repository"

	mock "github.com/stretchr/testify/mock"
)

// MockTaskHistoryRepository is an autogenerated mock type for the TaskHistoryRepository type
type MockTaskHistoryRepository struct {
	mock.Mock
}

type MockTaskHistoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskHistoryRepository) EXPECT() *MockTaskHistoryRepository_Expecter {
	return &MockTaskHistoryRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, request
func (_m *MockTaskHistoryRepository) Add(ctx context.Context, request repository.AddTaskHistoryRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.AddTaskHistoryRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskHistoryRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockTaskHistoryRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - request repository.AddTaskHistoryRequest
func (_e *MockTaskHistoryRepository_Expecter) Add(ctx interface{}, request interface{}) *MockTaskHistoryRepository_Add_Call {
	return &MockTaskHistoryRepository_Add_Call{Call: _e.mock.On("Add", ctx, request)}
}

func (_c *MockTaskHistoryRepository_Add_Call) Run(run func(ctx context.Context, request repository.AddTaskHistoryRequest)) *MockTaskHistoryRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.AddTaskHistoryRequest))
	})
	return _c
}

func (_c *MockTaskHistoryRepository_Add_Call) Return(_a0 error) *MockTaskHistoryRepository_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskHistoryRepository_Add_Call) RunAndReturn(run func(context.Context, repository.AddTaskHistoryRequest) error) *MockTaskHistoryRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTask provides a mock function with given fields: ctx, taskID
func (_m *MockTaskHistoryRepository) ListByTask(ctx context.Context, taskID int64) ([]entity.TaskHistory, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTask")
	}

	var r0 []entity.TaskHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]entity.TaskHistory, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []entity.TaskHistory); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TaskHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskHistoryRepository_ListByTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTask'
type MockTaskHistoryRepository_ListByTask_Call struct {
	*mock.Call
}

// ListByTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID int64
func (_e *MockTaskHistoryRepository_Expecter) ListByTask(ctx interface{}, taskID interface{}) *MockTaskHistoryRepository_ListByTask_Call {
	return &MockTaskHistoryRepository_ListByTask_Call{Call: _e.mock.On("ListByTask", ctx, taskID)}
}

func (_c *MockTaskHistoryRepository_ListByTask_Call) Run(run func(ctx context.Context, taskID int64)) *MockTaskHistoryRepository_ListByTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTaskHistoryRepository_ListByTask_Call) Return(_a0 []entity.TaskHistory, _a1 error) *MockTaskHistoryRepository_ListByTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskHistoryRepository_ListByTask_Call) RunAndReturn(run func(context.Context, int64) ([]entity.TaskHistory, error)) *MockTaskHistoryRepository_ListByTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskHistoryRepository creates a new instance of MockTaskHistoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskHistoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskHistoryRepository {
	mock := &MockTaskHistoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
