// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "taskmanager/internal/entity"
	repository "taskmanager/internal/repository"

	mock "github.com/stretchr/testify/mock"
)

// MockTaskRepository is an autogenerated mock type for the TaskRepository type
type MockTaskRepository struct {
	mock.Mock
}

type MockTaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskRepository) EXPECT() *MockTaskRepository_Expecter {
	return &MockTaskRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, request
func (_m *MockTaskRepository) Create(ctx context.Context, request repository.CreateTaskRequest) (*entity.Task, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateTaskRequest) (*entity.Task, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateTaskRequest) *entity.Task); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateTaskRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTaskRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - request repository.CreateTaskRequest
func (_e *MockTaskRepository_Expecter) Create(ctx interface{}, request interface{}) *MockTaskRepository_Create_Call {
	return &MockTaskRepository_Create_Call{Call: _e.mock.On("Create", ctx, request)}
}

func (_c *MockTaskRepository_Create_Call) Run(run func(ctx context.Context, request repository.CreateTaskRequest)) *MockTaskRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.CreateTaskRequest))
	})
	return _c
}

func (_c *MockTaskRepository_Create_Call) Return(_a0 *entity.Task, _a1 error) *MockTaskRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_Create_Call) RunAndReturn(run func(context.Context, repository.CreateTaskRequest) (*entity.Task, error)) *MockTaskRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockTaskRepository) GetByID(ctx context.Context, id int64) (*entity.Task, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.Task, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.Task); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTaskRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockTaskRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTaskRepository_GetByID_Call {
	return &MockTaskRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTaskRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockTaskRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTaskRepository_GetByID_Call) Return(_a0 *entity.Task, _a1 error) *MockTaskRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*entity.Task, error)) *MockTaskRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockTaskRepository) List(ctx context.Context, filter repository.ListTasksFilter) ([]entity.Task, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListTasksFilter) ([]entity.Task, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListTasksFilter) []entity.Task); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.ListTasksFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTaskRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repository.ListTasksFilter
func (_e *MockTaskRepository_Expecter) List(ctx interface{}, filter interface{}) *MockTaskRepository_List_Call {
	return &MockTaskRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockTaskRepository_List_Call) Run(run func(ctx context.Context, filter repository.ListTasksFilter)) *MockTaskRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.ListTasksFilter))
	})
	return _c
}

func (_c *MockTaskRepository_List_Call) Return(_a0 []entity.Task, _a1 error) *MockTaskRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_List_Call) RunAndReturn(run func(context.Context, repository.ListTasksFilter) ([]entity.Task, error)) *MockTaskRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, request
func (_m *MockTaskRepository) Update(ctx context.Context, request repository.UpdateTaskRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateTaskRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTaskRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - request repository.UpdateTaskRequest
func (_e *MockTaskRepository_Expecter) Update(ctx interface{}, request interface{}) *MockTaskRepository_Update_Call {
	return &MockTaskRepository_Update_Call{Call: _e.mock.On("Update", ctx, request)}
}

func (_c *MockTaskRepository_Update_Call) Run(run func(ctx context.Context, request repository.UpdateTaskRequest)) *MockTaskRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.UpdateTaskRequest))
	})
	return _c
}

func (_c *MockTaskRepository_Update_Call) Return(_a0 error) *MockTaskRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskRepository_Update_Call) RunAndReturn(run func(context.Context, repository.UpdateTaskRequest) error) *MockTaskRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskRepository creates a new instance of MockTaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskRepository {
	mock := &MockTaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
