// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "taskmanager/internal/entity"
	repository "taskmanager/internal/repository"

	mock "github.com/stretchr/testify/mock"
)

// MockTeamRepository is an autogenerated mock type for the TeamRepository type
type MockTeamRepository struct {
	mock.Mock
}

type MockTeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamRepository) EXPECT() *MockTeamRepository_Expecter {
	return &MockTeamRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, request
func (_m *MockTeamRepository) Create(ctx context.Context, request repository.CreateTeamRequest) (*entity.Team, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateTeamRequest) (*entity.Team, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateTeamRequest) *entity.Team); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateTeamRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTeamRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - request repository.CreateTeamRequest
func (_e *MockTeamRepository_Expecter) Create(ctx interface{}, request interface{}) *MockTeamRepository_Create_Call {
	return &MockTeamRepository_Create_Call{Call: _e.mock.On("Create", ctx, request)}
}

func (_c *MockTeamRepository_Create_Call) Run(run func(ctx context.Context, request repository.CreateTeamRequest)) *MockTeamRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.CreateTeamRequest))
	})
	return _c
}

func (_c *MockTeamRepository_Create_Call) Return(_a0 *entity.Team, _a1 error) *MockTeamRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamRepository_Create_Call) RunAndReturn(run func(context.Context, repository.CreateTeamRequest) (*entity.Team, error)) *MockTeamRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockTeamRepository) GetByID(ctx context.Context, id int64) (*entity.Team, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.Team, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.Team); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTeamRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockTeamRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTeamRepository_GetByID_Call {
	return &MockTeamRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTeamRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockTeamRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTeamRepository_GetByID_Call) Return(_a0 *entity.Team, _a1 error) *MockTeamRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*entity.Team, error)) *MockTeamRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID
func (_m *MockTeamRepository) ListByUser(ctx context.Context, userID int64) ([]entity.Team, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []entity.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]entity.Team, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []entity.Team); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockTeamRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockTeamRepository_Expecter) ListByUser(ctx interface{}, userID interface{}) *MockTeamRepository_ListByUser_Call {
	return &MockTeamRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockTeamRepository_ListByUser_Call) Run(run func(ctx context.Context, userID int64)) *MockTeamRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTeamRepository_ListByUser_Call) Return(_a0 []entity.Team, _a1 error) *MockTeamRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamRepository_ListByUser_Call) RunAndReturn(run func(context.Context, int64) ([]entity.Team, error)) *MockTeamRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamRepository creates a new instance of MockTeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamRepository {
	mock := &MockTeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
