// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockTokenIssuer is an autogenerated mock type for the TokenIssuer type
type MockTokenIssuer struct {
	mock.Mock
}

type MockTokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenIssuer) EXPECT() *MockTokenIssuer_Expecter {
	return &MockTokenIssuer_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: userID
func (_m *MockTokenIssuer) Generate(userID int64) (string, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (string, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int64) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenIssuer_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockTokenIssuer_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - userID int64
func (_e *MockTokenIssuer_Expecter) Generate(userID interface{}) *MockTokenIssuer_Generate_Call {
	return &MockTokenIssuer_Generate_Call{Call: _e.mock.On("Generate", userID)}
}

func (_c *MockTokenIssuer_Generate_Call) Run(run func(userID int64)) *MockTokenIssuer_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockTokenIssuer_Generate_Call) Return(_a0 string, _a1 error) *MockTokenIssuer_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenIssuer_Generate_Call) RunAndReturn(run func(int64) (string, error)) *MockTokenIssuer_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenIssuer creates a new instance of MockTokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenIssuer {
	mock := &MockTokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
