// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "taskmanager/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockMembershipRepository is an autogenerated mock type for the MembershipRepository type
type MockMembershipRepository struct {
	mock.Mock
}

type MockMembershipRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMembershipRepository) EXPECT() *MockMembershipRepository_Expecter {
	return &MockMembershipRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, teamID, userID
func (_m *MockMembershipRepository) Get(ctx context.Context, teamID int64, userID int64) (*entity.TeamMember, error) {
	ret := _m.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*entity.TeamMember, error)); ok {
		return rf(ctx, teamID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *entity.TeamMember); ok {
		r0 = rf(ctx, teamID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, teamID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMembershipRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMembershipRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID int64
//   - userID int64
func (_e *MockMembershipRepository_Expecter) Get(ctx interface{}, teamID interface{}, userID interface{}) *MockMembershipRepository_Get_Call {
	return &MockMembershipRepository_Get_Call{Call: _e.mock.On("Get", ctx, teamID, userID)}
}

func (_c *MockMembershipRepository_Get_Call) Run(run func(ctx context.Context, teamID int64, userID int64)) *MockMembershipRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockMembershipRepository_Get_Call) Return(_a0 *entity.TeamMember, _a1 error) *MockMembershipRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMembershipRepository_Get_Call) RunAndReturn(run func(context.Context, int64, int64) (*entity.TeamMember, error)) *MockMembershipRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMembershipRepository creates a new instance of MockMembershipRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMembershipRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMembershipRepository {
	mock := &MockMembershipRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
