// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "taskmanager/internal/entity"
	repository "taskmanager/internal/repository"

	mock "github.com/stretchr/testify/mock"
)

// MockCommentRepository is an autogenerated mock type for the CommentRepository type
type MockCommentRepository struct {
	mock.Mock
}

type MockCommentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommentRepository) EXPECT() *MockCommentRepository_Expecter {
	return &MockCommentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, request
func (_m *MockCommentRepository) Create(ctx context.Context, request repository.CreateTaskCommentRequest) (*entity.TaskComment, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.TaskComment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateTaskCommentRequest) (*entity.TaskComment, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateTaskCommentRequest) *entity.TaskComment); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TaskComment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateTaskCommentRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCommentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - request repository.CreateTaskCommentRequest
func (_e *MockCommentRepository_Expecter) Create(ctx interface{}, request interface{}) *MockCommentRepository_Create_Call {
	return &MockCommentRepository_Create_Call{Call: _e.mock.On("Create", ctx, request)}
}

func (_c *MockCommentRepository_Create_Call) Run(run func(ctx context.Context, request repository.CreateTaskCommentRequest)) *MockCommentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.CreateTaskCommentRequest))
	})
	return _c
}

func (_c *MockCommentRepository_Create_Call) Return(_a0 *entity.TaskComment, _a1 error) *MockCommentRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommentRepository_Create_Call) RunAndReturn(run func(context.Context, repository.CreateTaskCommentRequest) (*entity.TaskComment, error)) *MockCommentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTask provides a mock function with given fields: ctx, taskID
func (_m *MockCommentRepository) ListByTask(ctx context.Context, taskID int64) ([]entity.TaskComment, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTask")
	}

	var r0 []entity.TaskComment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]entity.TaskComment, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []entity.TaskComment); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TaskComment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentRepository_ListByTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTask'
type MockCommentRepository_ListByTask_Call struct {
	*mock.Call
}

// ListByTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID int64
func (_e *MockCommentRepository_Expecter) ListByTask(ctx interface{}, taskID interface{}) *MockCommentRepository_ListByTask_Call {
	return &MockCommentRepository_ListByTask_Call{Call: _e.mock.On("ListByTask", ctx, taskID)}
}

func (_c *MockCommentRepository_ListByTask_Call) Run(run func(ctx context.Context, taskID int64)) *MockCommentRepository_ListByTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockCommentRepository_ListByTask_Call) Return(_a0 []entity.TaskComment, _a1 error) *MockCommentRepository_ListByTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommentRepository_ListByTask_Call) RunAndReturn(run func(context.Context, int64) ([]entity.TaskComment, error)) *MockCommentRepository_ListByTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommentRepository creates a new instance of MockCommentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommentRepository {
	mock := &MockCommentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
