// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "taskmanager/internal/entity"
	repository "taskmanager/internal/repository"

	mock "github.com/stretchr/testify/mock"
)

// MockTeamMemberRepository is an autogenerated mock type for the TeamMemberRepository type
type MockTeamMemberRepository struct {
	mock.Mock
}

type MockTeamMemberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamMemberRepository) EXPECT() *MockTeamMemberRepository_Expecter {
	return &MockTeamMemberRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, request
func (_m *MockTeamMemberRepository) Add(ctx context.Context, request repository.AddTeamMemberRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.AddTeamMemberRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamMemberRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockTeamMemberRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - request repository.AddTeamMemberRequest
func (_e *MockTeamMemberRepository_Expecter) Add(ctx interface{}, request interface{}) *MockTeamMemberRepository_Add_Call {
	return &MockTeamMemberRepository_Add_Call{Call: _e.mock.On("Add", ctx, request)}
}

func (_c *MockTeamMemberRepository_Add_Call) Run(run func(ctx context.Context, request repository.AddTeamMemberRequest)) *MockTeamMemberRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.AddTeamMemberRequest))
	})
	return _c
}

func (_c *MockTeamMemberRepository_Add_Call) Return(_a0 error) *MockTeamMemberRepository_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamMemberRepository_Add_Call) RunAndReturn(run func(context.Context, repository.AddTeamMemberRequest) error) *MockTeamMemberRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, teamID, userID
func (_m *MockTeamMemberRepository) Get(ctx context.Context, teamID int64, userID int64) (*entity.TeamMember, error) {
	ret := _m.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*entity.TeamMember, error)); ok {
		return rf(ctx, teamID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *entity.TeamMember); ok {
		r0 = rf(ctx, teamID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, teamID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamMemberRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTeamMemberRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID int64
//   - userID int64
func (_e *MockTeamMemberRepository_Expecter) Get(ctx interface{}, teamID interface{}, userID interface{}) *MockTeamMemberRepository_Get_Call {
	return &MockTeamMemberRepository_Get_Call{Call: _e.mock.On("Get", ctx, teamID, userID)}
}

func (_c *MockTeamMemberRepository_Get_Call) Run(run func(ctx context.Context, teamID int64, userID int64)) *MockTeamMemberRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockTeamMemberRepository_Get_Call) Return(_a0 *entity.TeamMember, _a1 error) *MockTeamMemberRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamMemberRepository_Get_Call) RunAndReturn(run func(context.Context, int64, int64) (*entity.TeamMember, error)) *MockTeamMemberRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamMemberRepository creates a new instance of MockTeamMemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamMemberRepository {
	mock := &MockTeamMemberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
