// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "taskmanager/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockTaskCache is an autogenerated mock type for the TaskCache type
type MockTaskCache struct {
	mock.Mock
}

type MockTaskCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskCache) EXPECT() *MockTaskCache_Expecter {
	return &MockTaskCache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockTaskCache) Get(ctx context.Context, key string) ([]entity.Task, bool, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []entity.Task
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entity.Task, bool, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entity.Task); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, key)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTaskCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTaskCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockTaskCache_Expecter) Get(ctx interface{}, key interface{}) *MockTaskCache_Get_Call {
	return &MockTaskCache_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockTaskCache_Get_Call) Run(run func(ctx context.Context, key string)) *MockTaskCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskCache_Get_Call) Return(_a0 []entity.Task, _a1 bool, _a2 error) *MockTaskCache_Get_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTaskCache_Get_Call) RunAndReturn(run func(context.Context, string) ([]entity.Task, bool, error)) *MockTaskCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateTeam provides a mock function with given fields: ctx, teamID
func (_m *MockTaskCache) InvalidateTeam(ctx context.Context, teamID int64) error {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskCache_InvalidateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateTeam'
type MockTaskCache_InvalidateTeam_Call struct {
	*mock.Call
}

// InvalidateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID int64
func (_e *MockTaskCache_Expecter) InvalidateTeam(ctx interface{}, teamID interface{}) *MockTaskCache_InvalidateTeam_Call {
	return &MockTaskCache_InvalidateTeam_Call{Call: _e.mock.On("InvalidateTeam", ctx, teamID)}
}

func (_c *MockTaskCache_InvalidateTeam_Call) Run(run func(ctx context.Context, teamID int64)) *MockTaskCache_InvalidateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTaskCache_InvalidateTeam_Call) Return(_a0 error) *MockTaskCache_InvalidateTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskCache_InvalidateTeam_Call) RunAndReturn(run func(context.Context, int64) error) *MockTaskCache_InvalidateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, tasks
func (_m *MockTaskCache) Set(ctx context.Context, key string, tasks []entity.Task) error {
	ret := _m.Called(ctx, key, tasks)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []entity.Task) error); ok {
		r0 = rf(ctx, key, tasks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockTaskCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - tasks []entity.Task
func (_e *MockTaskCache_Expecter) Set(ctx interface{}, key interface{}, tasks interface{}) *MockTaskCache_Set_Call {
	return &MockTaskCache_Set_Call{Call: _e.mock.On("Set", ctx, key, tasks)}
}

func (_c *MockTaskCache_Set_Call) Run(run func(ctx context.Context, key string, tasks []entity.Task)) *MockTaskCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]entity.Task))
	})
	return _c
}

func (_c *MockTaskCache_Set_Call) Return(_a0 error) *MockTaskCache_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskCache_Set_Call) RunAndReturn(run func(context.Context, string, []entity.Task) error) *MockTaskCache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskCache creates a new instance of MockTaskCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskCache {
	mock := &MockTaskCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
