// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "taskmanager/internal/entity"
	service "taskmanager/internal/service"

	mock "github.com/stretchr/testify/mock"
)

// MockRegistrar is an autogenerated mock type for the Registrar type
type MockRegistrar struct {
	mock.Mock
}

type MockRegistrar_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistrar) EXPECT() *MockRegistrar_Expecter {
	return &MockRegistrar_Expecter{mock: &_m.Mock}
}

// Register provides a mock function with given fields: ctx, cmd
func (_m *MockRegistrar) Register(ctx context.Context, cmd service.RegisterCommand) (*entity.User, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.RegisterCommand) (*entity.User, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.RegisterCommand) *entity.User); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.RegisterCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegistrar_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockRegistrar_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd service.RegisterCommand
func (_e *MockRegistrar_Expecter) Register(ctx interface{}, cmd interface{}) *MockRegistrar_Register_Call {
	return &MockRegistrar_Register_Call{Call: _e.mock.On("Register", ctx, cmd)}
}

func (_c *MockRegistrar_Register_Call) Run(run func(ctx context.Context, cmd service.RegisterCommand)) *MockRegistrar_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.RegisterCommand))
	})
	return _c
}

func (_c *MockRegistrar_Register_Call) Return(_a0 *entity.User, _a1 error) *MockRegistrar_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegistrar_Register_Call) RunAndReturn(run func(context.Context, service.RegisterCommand) (*entity.User, error)) *MockRegistrar_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRegistrar creates a new instance of MockRegistrar. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistrar(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistrar {
	mock := &MockRegistrar{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
