// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	service "taskmanager/internal/service"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthenticator is an autogenerated mock type for the Authenticator type
type MockAuthenticator struct {
	mock.Mock
}

type MockAuthenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthenticator) EXPECT() *MockAuthenticator_Expecter {
	return &MockAuthenticator_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, cmd
func (_m *MockAuthenticator) Login(ctx context.Context, cmd service.LoginCommand) (string, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.LoginCommand) (string, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.LoginCommand) string); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.LoginCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthenticator_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthenticator_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd service.LoginCommand
func (_e *MockAuthenticator_Expecter) Login(ctx interface{}, cmd interface{}) *MockAuthenticator_Login_Call {
	return &MockAuthenticator_Login_Call{Call: _e.mock.On("Login", ctx, cmd)}
}

func (_c *MockAuthenticator_Login_Call) Run(run func(ctx context.Context, cmd service.LoginCommand)) *MockAuthenticator_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.LoginCommand))
	})
	return _c
}

func (_c *MockAuthenticator_Login_Call) Return(_a0 string, _a1 error) *MockAuthenticator_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthenticator_Login_Call) RunAndReturn(run func(context.Context, service.LoginCommand) (string, error)) *MockAuthenticator_Login_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthenticator creates a new instance of MockAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthenticator {
	mock := &MockAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
