// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	repository "taskmanager/internal/repository"

	mock "github.com/stretchr/testify/mock"
)

// MockAnalytics is an autogenerated mock type for the Analytics type
type MockAnalytics struct {
	mock.Mock
}

type MockAnalytics_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnalytics) EXPECT() *MockAnalytics_Expecter {
	return &MockAnalytics_Expecter{mock: &_m.Mock}
}

// InconsistentTasks provides a mock function with given fields: ctx
func (_m *MockAnalytics) InconsistentTasks(ctx context.Context) ([]repository.InconsistentTask, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InconsistentTasks")
	}

	var r0 []repository.InconsistentTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]repository.InconsistentTask, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []repository.InconsistentTask); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.InconsistentTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAnalytics_InconsistentTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InconsistentTasks'
type MockAnalytics_InconsistentTasks_Call struct {
	*mock.Call
}

// InconsistentTasks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAnalytics_Expecter) InconsistentTasks(ctx interface{}) *MockAnalytics_InconsistentTasks_Call {
	return &MockAnalytics_InconsistentTasks_Call{Call: _e.mock.On("InconsistentTasks", ctx)}
}

func (_c *MockAnalytics_InconsistentTasks_Call) Run(run func(ctx context.Context)) *MockAnalytics_InconsistentTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAnalytics_InconsistentTasks_Call) Return(_a0 []repository.InconsistentTask, _a1 error) *MockAnalytics_InconsistentTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAnalytics_InconsistentTasks_Call) RunAndReturn(run func(context.Context) ([]repository.InconsistentTask, error)) *MockAnalytics_InconsistentTasks_Call {
	_c.Call.Return(run)
	return _c
}

// TeamStats provides a mock function with given fields: ctx
func (_m *MockAnalytics) TeamStats(ctx context.Context) ([]repository.TeamStats, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TeamStats")
	}

	var r0 []repository.TeamStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]repository.TeamStats, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []repository.TeamStats); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.TeamStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAnalytics_TeamStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TeamStats'
type MockAnalytics_TeamStats_Call struct {
	*mock.Call
}

// TeamStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAnalytics_Expecter) TeamStats(ctx interface{}) *MockAnalytics_TeamStats_Call {
	return &MockAnalytics_TeamStats_Call{Call: _e.mock.On("TeamStats", ctx)}
}

func (_c *MockAnalytics_TeamStats_Call) Run(run func(ctx context.Context)) *MockAnalytics_TeamStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAnalytics_TeamStats_Call) Return(_a0 []repository.TeamStats, _a1 error) *MockAnalytics_TeamStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAnalytics_TeamStats_Call) RunAndReturn(run func(context.Context) ([]repository.TeamStats, error)) *MockAnalytics_TeamStats_Call {
	_c.Call.Return(run)
	return _c
}

// TopCreatorsPerTeam provides a mock function with given fields: ctx
func (_m *MockAnalytics) TopCreatorsPerTeam(ctx context.Context) ([]repository.TopCreator, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TopCreatorsPerTeam")
	}

	var r0 []repository.TopCreator
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]repository.TopCreator, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []repository.TopCreator); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.TopCreator)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAnalytics_TopCreatorsPerTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TopCreatorsPerTeam'
type MockAnalytics_TopCreatorsPerTeam_Call struct {
	*mock.Call
}

// TopCreatorsPerTeam is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAnalytics_Expecter) TopCreatorsPerTeam(ctx interface{}) *MockAnalytics_TopCreatorsPerTeam_Call {
	return &MockAnalytics_TopCreatorsPerTeam_Call{Call: _e.mock.On("TopCreatorsPerTeam", ctx)}
}

func (_c *MockAnalytics_TopCreatorsPerTeam_Call) Run(run func(ctx context.Context)) *MockAnalytics_TopCreatorsPerTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAnalytics_TopCreatorsPerTeam_Call) Return(_a0 []repository.TopCreator, _a1 error) *MockAnalytics_TopCreatorsPerTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAnalytics_TopCreatorsPerTeam_Call) RunAndReturn(run func(context.Context) ([]repository.TopCreator, error)) *MockAnalytics_TopCreatorsPerTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAnalytics creates a new instance of MockAnalytics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalytics(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalytics {
	mock := &MockAnalytics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
